export const SET_ACCOUNT_INFO = 'SET_ACCOUNT_INFO';

export const SET_MY_SHARES = 'SET_MY_SHARES';

export const SET_OPEN_SHARES = 'SET_OPEN_SHARES';

export const SET_PARTICIPATION_SHARES = 'SET_PARTICIPATION_SHARES';

export const SET_SHOW_DETAIL = 'SET_SHOW_DETAIL';

export const SET_SHARE_DETAIL = 'SET_SHARE_DETAIL';

export const SET_CONNECTING = 'SET_CONNECTING';

export const ADD_PENDING_TX = 'ADD_PENDING_TX';

export const SET_PENDING_TX = 'SET_PENDING_TX';
